
CREATE TABLE STORE_USER(
	USERID VARCHAR2(20) PRIMARY KEY,
    USERPW VARCHAR2(100) NOT NULL,
    USERNAME VARCHAR2(60) UNIQUE,
    enabled number(1) default 1 check(enabled = 0 or enabled = 1),
    rolename varchar2(10) default 'ROLE_USER' check(rolename = 'ROLE_ADMIN' or rolename = 'ROLE_USER'));
    
CREATE TABLE STORE_BOOK(
    BOOKNUM NUMBER PRIMARY KEY,
    BOOKNAME VARCHAR2(200) UNIQUE,
    BOOK_DESCRIPTION VARCHAR2(2000) NOT NULL,
    BOOKPRICE NUMBER NOT NULL);
    
CREATE TABLE STORE_ORDER(
    ORDERNUM NUMBER PRIMARY KEY,
    BOOKNAME VARCHAR2(200) REFERENCES STORE_BOOK(BOOKNAME) ON DELETE CASCADE,
    USERID VARCHAR2(20) REFERENCES STORE_USER(USERID) ON DELETE CASCADE,
    USERNAME VARCHAR2(60) REFERENCES STORE_USER(USERNAME) ON DELETE CASCADE,
    ALLPRICE NUMBER NOT NULL,
    ADDRESS VARCHAR2(2000) NOT NULL);
    
CREATE SEQUENCE bookNum_seq;
CREATE SEQUENCE orderNum_seq;